.PHONY: clean All

All:
	@echo "----------Building project:[ OutFirstProgram - Debug ]----------"
	@cd "OutFirstProgram" && "$(MAKE)" -f  "OutFirstProgram.mk"
clean:
	@echo "----------Cleaning project:[ OutFirstProgram - Debug ]----------"
	@cd "OutFirstProgram" && "$(MAKE)" -f  "OutFirstProgram.mk" clean
