#!/bin/bash
# LLDB Step-by-Step Debugging Guide
# This file shows you how to debug line by line

echo "=== LLDB Step-by-Step Debugging Guide ==="
echo ""
echo "1. START LLDB:"
echo "   $ lldb ./14_136_schoolManagement"
echo ""
echo "2. SET BREAKPOINT AT MAIN:"
echo "   (lldb) breakpoint set --name main"
echo "   (lldb) b main"
echo ""
echo "3. RUN THE PROGRAM:"
echo "   (lldb) run"
echo "   (lldb) r"
echo ""
echo "4. STEP THROUGH CODE LINE BY LINE:"
echo "   (lldb) next       # Execute next line (step over functions)"
echo "   (lldb) n          # Short form"
echo "   (lldb) step       # Step INTO functions"
echo "   (lldb) s          # Short form"
echo ""
echo "5. VIEW VARIABLES AT ANY TIME:"
echo "   (lldb) frame variable              # Show all local variables"
echo "   (lldb) fr v                        # Short form"
echo "   (lldb) print variableName          # Print specific variable"
echo "   (lldb) p variableName              # Short form"
echo ""
echo "6. INSPECT POINTERS AND STRUCTS:"
echo "   (lldb) p mySchool                  # Print pointer address"
echo "   (lldb) p *mySchool                 # Dereference pointer"
echo "   (lldb) p mySchool->name            # Access struct member"
echo "   (lldb) fr v -R mySchool            # Show EVERYTHING recursively"
echo ""
echo "7. VIEW SOURCE CODE:"
echo "   (lldb) list                        # Show current code"
echo "   (lldb) l                           # Short form"
echo ""
echo "8. CONTINUE OR FINISH:"
echo "   (lldb) continue                    # Continue to next breakpoint"
echo "   (lldb) c                           # Short form"
echo "   (lldb) finish                      # Run until current function returns"
echo ""
echo "9. EXIT LLDB:"
echo "   (lldb) quit"
echo "   (lldb) q"
echo ""
echo "=== PRACTICAL EXAMPLE SESSION ==="
echo ""
echo "$ lldb ./14_136_schoolManagement"
echo "(lldb) b main"
echo "Breakpoint 1: where = 14_136_schoolManagement\`main"
echo ""
echo "(lldb) run"
echo "Process 12345 launched"
echo "Enter school name: MIT"
echo ""
echo "(lldb) next    # Execute one line"
echo "(lldb) n       # Keep pressing 'n' to go line by line"
echo "(lldb) n"
echo "(lldb) n"
echo ""
echo "(lldb) frame variable    # See all variables"
echo "(lldb) p mySchool        # Check mySchool pointer"
echo ""
echo "(lldb) n    # After mySchool is created"
echo "(lldb) p mySchool->name"
echo "(lldb) p mySchool->totalCourses"
echo ""
echo "(lldb) continue    # Let program finish"
echo "(lldb) quit"
