.PHONY: clean All

All:
	@echo "----------Building project:[ FormatSpecifier - Debug ]----------"
	@cd "FormatSpecifier" && "$(MAKE)" -f  "FormatSpecifier.mk"
clean:
	@echo "----------Cleaning project:[ FormatSpecifier - Debug ]----------"
	@cd "FormatSpecifier" && "$(MAKE)" -f  "FormatSpecifier.mk" clean
