.PHONY: clean All

All:
	@echo "----------Building project:[ test_double - Debug ]----------"
	@cd "test_double" && "$(MAKE)" -f  "test_double.mk"
clean:
	@echo "----------Cleaning project:[ test_double - Debug ]----------"
	@cd "test_double" && "$(MAKE)" -f  "test_double.mk" clean
